// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/time"
	"github.com/bborbe/vault-ui/pkg/sessionsnapshot"
)

type Snapshot struct {
	GenerationStub        func() uint64
	generationMutex       sync.RWMutex
	generationArgsForCall []struct{}
	generationReturns     struct {
		result1 uint64
	}
	generationReturnsOnCall map[int]struct {
		result1 uint64
	}
	RefreshOnceStub        func(context.Context) error
	refreshOnceMutex       sync.RWMutex
	refreshOnceArgsForCall []SnapshotRefreshOnceArgs
	refreshOnceReturns     struct {
		result1 error
	}
	refreshOnceReturnsOnCall map[int]struct {
		result1 error
	}
	RegistrySessionIDsStub        func(context.Context) []string
	registrySessionIDsMutex       sync.RWMutex
	registrySessionIDsArgsForCall []SnapshotRegistrySessionIDsArgs
	registrySessionIDsReturns     struct {
		result1 []string
	}
	registrySessionIDsReturnsOnCall map[int]struct {
		result1 []string
	}
	ResumeSessionIDsStub        func(context.Context) []string
	resumeSessionIDsMutex       sync.RWMutex
	resumeSessionIDsArgsForCall []SnapshotResumeSessionIDsArgs
	resumeSessionIDsReturns     struct {
		result1 []string
	}
	resumeSessionIDsReturnsOnCall map[int]struct {
		result1 []string
	}
	RunStub        func(context.Context) error
	runMutex       sync.RWMutex
	runArgsForCall []SnapshotRunArgs
	runReturns     struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	TranscriptMtimeStub        func(context.Context, string, string, string) *time.DateTime
	transcriptMtimeMutex       sync.RWMutex
	transcriptMtimeArgsForCall []SnapshotTranscriptMtimeArgs
	transcriptMtimeReturns     struct {
		result1 *time.DateTime
	}
	transcriptMtimeReturnsOnCall map[int]struct {
		result1 *time.DateTime
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// SnapshotRefreshOnceArgs holds the arguments of one call to RefreshOnce.
type SnapshotRefreshOnceArgs struct {
	Arg1 context.Context
}

// SnapshotRegistrySessionIDsArgs holds the arguments of one call to RegistrySessionIDs.
type SnapshotRegistrySessionIDsArgs struct {
	Arg1 context.Context
}

// SnapshotResumeSessionIDsArgs holds the arguments of one call to ResumeSessionIDs.
type SnapshotResumeSessionIDsArgs struct {
	Arg1 context.Context
}

// SnapshotRunArgs holds the arguments of one call to Run.
type SnapshotRunArgs struct {
	Arg1 context.Context
}

// SnapshotTranscriptMtimeArgs holds the arguments of one call to TranscriptMtime.
type SnapshotTranscriptMtimeArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
	Arg4 string
}

func (fake *Snapshot) Generation() uint64 {
	fake.generationMutex.Lock()
	ret, specificReturn := fake.generationReturnsOnCall[len(fake.generationArgsForCall)]
	fake.generationArgsForCall = append(fake.generationArgsForCall, struct{}{})
	stub := fake.GenerationStub
	fakeReturns := fake.generationReturns
	fake.recordInvocation("Generation", []interface{}{})
	fake.generationMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Snapshot) GenerationCallCount() int {
	fake.generationMutex.RLock()
	defer fake.generationMutex.RUnlock()
	return len(fake.generationArgsForCall)
}

func (fake *Snapshot) GenerationCalls(stub func() uint64) {
	fake.generationMutex.Lock()
	defer fake.generationMutex.Unlock()
	fake.GenerationStub = stub
}

func (fake *Snapshot) GenerationReturns(result1 uint64) {
	fake.generationMutex.Lock()
	defer fake.generationMutex.Unlock()
	fake.GenerationStub = nil
	fake.generationReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *Snapshot) GenerationReturnsOnCall(i int, result1 uint64) {
	fake.generationMutex.Lock()
	defer fake.generationMutex.Unlock()
	fake.GenerationStub = nil
	if fake.generationReturnsOnCall == nil {
		fake.generationReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.generationReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *Snapshot) RefreshOnce(arg1 context.Context) error {
	fake.refreshOnceMutex.Lock()
	ret, specificReturn := fake.refreshOnceReturnsOnCall[len(fake.refreshOnceArgsForCall)]
	fake.refreshOnceArgsForCall = append(fake.refreshOnceArgsForCall, SnapshotRefreshOnceArgs{arg1})
	stub := fake.RefreshOnceStub
	fakeReturns := fake.refreshOnceReturns
	fake.recordInvocation("RefreshOnce", []interface{}{arg1})
	fake.refreshOnceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Snapshot) RefreshOnceCallCount() int {
	fake.refreshOnceMutex.RLock()
	defer fake.refreshOnceMutex.RUnlock()
	return len(fake.refreshOnceArgsForCall)
}

func (fake *Snapshot) RefreshOnceCalls(stub func(context.Context) error) {
	fake.refreshOnceMutex.Lock()
	defer fake.refreshOnceMutex.Unlock()
	fake.RefreshOnceStub = stub
}

func (fake *Snapshot) RefreshOnceArgsForCall(i int) context.Context {
	fake.refreshOnceMutex.RLock()
	defer fake.refreshOnceMutex.RUnlock()
	argsForCall := fake.refreshOnceArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *Snapshot) RefreshOnceArgs() []SnapshotRefreshOnceArgs {
	fake.refreshOnceMutex.RLock()
	defer fake.refreshOnceMutex.RUnlock()
	args := make([]SnapshotRefreshOnceArgs, len(fake.refreshOnceArgsForCall))
	copy(args, fake.refreshOnceArgsForCall)
	return args
}

func (fake *Snapshot) RefreshOnceReturns(result1 error) {
	fake.refreshOnceMutex.Lock()
	defer fake.refreshOnceMutex.Unlock()
	fake.RefreshOnceStub = nil
	fake.refreshOnceReturns = struct {
		result1 error
	}{result1}
}

func (fake *Snapshot) RefreshOnceReturnsOnCall(i int, result1 error) {
	fake.refreshOnceMutex.Lock()
	defer fake.refreshOnceMutex.Unlock()
	fake.RefreshOnceStub = nil
	if fake.refreshOnceReturnsOnCall == nil {
		fake.refreshOnceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.refreshOnceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Snapshot) RegistrySessionIDs(arg1 context.Context) []string {
	fake.registrySessionIDsMutex.Lock()
	ret, specificReturn := fake.registrySessionIDsReturnsOnCall[len(fake.registrySessionIDsArgsForCall)]
	fake.registrySessionIDsArgsForCall = append(fake.registrySessionIDsArgsForCall, SnapshotRegistrySessionIDsArgs{arg1})
	stub := fake.RegistrySessionIDsStub
	fakeReturns := fake.registrySessionIDsReturns
	fake.recordInvocation("RegistrySessionIDs", []interface{}{arg1})
	fake.registrySessionIDsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Snapshot) RegistrySessionIDsCallCount() int {
	fake.registrySessionIDsMutex.RLock()
	defer fake.registrySessionIDsMutex.RUnlock()
	return len(fake.registrySessionIDsArgsForCall)
}

func (fake *Snapshot) RegistrySessionIDsCalls(stub func(context.Context) []string) {
	fake.registrySessionIDsMutex.Lock()
	defer fake.registrySessionIDsMutex.Unlock()
	fake.RegistrySessionIDsStub = stub
}

func (fake *Snapshot) RegistrySessionIDsArgsForCall(i int) context.Context {
	fake.registrySessionIDsMutex.RLock()
	defer fake.registrySessionIDsMutex.RUnlock()
	argsForCall := fake.registrySessionIDsArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *Snapshot) RegistrySessionIDsArgs() []SnapshotRegistrySessionIDsArgs {
	fake.registrySessionIDsMutex.RLock()
	defer fake.registrySessionIDsMutex.RUnlock()
	args := make([]SnapshotRegistrySessionIDsArgs, len(fake.registrySessionIDsArgsForCall))
	copy(args, fake.registrySessionIDsArgsForCall)
	return args
}

func (fake *Snapshot) RegistrySessionIDsReturns(result1 []string) {
	fake.registrySessionIDsMutex.Lock()
	defer fake.registrySessionIDsMutex.Unlock()
	fake.RegistrySessionIDsStub = nil
	fake.registrySessionIDsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *Snapshot) RegistrySessionIDsReturnsOnCall(i int, result1 []string) {
	fake.registrySessionIDsMutex.Lock()
	defer fake.registrySessionIDsMutex.Unlock()
	fake.RegistrySessionIDsStub = nil
	if fake.registrySessionIDsReturnsOnCall == nil {
		fake.registrySessionIDsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.registrySessionIDsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *Snapshot) ResumeSessionIDs(arg1 context.Context) []string {
	fake.resumeSessionIDsMutex.Lock()
	ret, specificReturn := fake.resumeSessionIDsReturnsOnCall[len(fake.resumeSessionIDsArgsForCall)]
	fake.resumeSessionIDsArgsForCall = append(fake.resumeSessionIDsArgsForCall, SnapshotResumeSessionIDsArgs{arg1})
	stub := fake.ResumeSessionIDsStub
	fakeReturns := fake.resumeSessionIDsReturns
	fake.recordInvocation("ResumeSessionIDs", []interface{}{arg1})
	fake.resumeSessionIDsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Snapshot) ResumeSessionIDsCallCount() int {
	fake.resumeSessionIDsMutex.RLock()
	defer fake.resumeSessionIDsMutex.RUnlock()
	return len(fake.resumeSessionIDsArgsForCall)
}

func (fake *Snapshot) ResumeSessionIDsCalls(stub func(context.Context) []string) {
	fake.resumeSessionIDsMutex.Lock()
	defer fake.resumeSessionIDsMutex.Unlock()
	fake.ResumeSessionIDsStub = stub
}

func (fake *Snapshot) ResumeSessionIDsArgsForCall(i int) context.Context {
	fake.resumeSessionIDsMutex.RLock()
	defer fake.resumeSessionIDsMutex.RUnlock()
	argsForCall := fake.resumeSessionIDsArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *Snapshot) ResumeSessionIDsArgs() []SnapshotResumeSessionIDsArgs {
	fake.resumeSessionIDsMutex.RLock()
	defer fake.resumeSessionIDsMutex.RUnlock()
	args := make([]SnapshotResumeSessionIDsArgs, len(fake.resumeSessionIDsArgsForCall))
	copy(args, fake.resumeSessionIDsArgsForCall)
	return args
}

func (fake *Snapshot) ResumeSessionIDsReturns(result1 []string) {
	fake.resumeSessionIDsMutex.Lock()
	defer fake.resumeSessionIDsMutex.Unlock()
	fake.ResumeSessionIDsStub = nil
	fake.resumeSessionIDsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *Snapshot) ResumeSessionIDsReturnsOnCall(i int, result1 []string) {
	fake.resumeSessionIDsMutex.Lock()
	defer fake.resumeSessionIDsMutex.Unlock()
	fake.ResumeSessionIDsStub = nil
	if fake.resumeSessionIDsReturnsOnCall == nil {
		fake.resumeSessionIDsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.resumeSessionIDsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *Snapshot) Run(arg1 context.Context) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, SnapshotRunArgs{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Snapshot) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *Snapshot) RunCalls(stub func(context.Context) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *Snapshot) RunArgsForCall(i int) context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *Snapshot) RunArgs() []SnapshotRunArgs {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	args := make([]SnapshotRunArgs, len(fake.runArgsForCall))
	copy(args, fake.runArgsForCall)
	return args
}

func (fake *Snapshot) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *Snapshot) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Snapshot) TranscriptMtime(arg1 context.Context, arg2 string, arg3 string, arg4 string) *time.DateTime {
	fake.transcriptMtimeMutex.Lock()
	ret, specificReturn := fake.transcriptMtimeReturnsOnCall[len(fake.transcriptMtimeArgsForCall)]
	fake.transcriptMtimeArgsForCall = append(fake.transcriptMtimeArgsForCall, SnapshotTranscriptMtimeArgs{arg1, arg2, arg3, arg4})
	stub := fake.TranscriptMtimeStub
	fakeReturns := fake.transcriptMtimeReturns
	fake.recordInvocation("TranscriptMtime", []interface{}{arg1, arg2, arg3, arg4})
	fake.transcriptMtimeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Snapshot) TranscriptMtimeCallCount() int {
	fake.transcriptMtimeMutex.RLock()
	defer fake.transcriptMtimeMutex.RUnlock()
	return len(fake.transcriptMtimeArgsForCall)
}

func (fake *Snapshot) TranscriptMtimeCalls(stub func(context.Context, string, string, string) *time.DateTime) {
	fake.transcriptMtimeMutex.Lock()
	defer fake.transcriptMtimeMutex.Unlock()
	fake.TranscriptMtimeStub = stub
}

func (fake *Snapshot) TranscriptMtimeArgsForCall(i int) (context.Context, string, string, string) {
	fake.transcriptMtimeMutex.RLock()
	defer fake.transcriptMtimeMutex.RUnlock()
	argsForCall := fake.transcriptMtimeArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *Snapshot) TranscriptMtimeArgs() []SnapshotTranscriptMtimeArgs {
	fake.transcriptMtimeMutex.RLock()
	defer fake.transcriptMtimeMutex.RUnlock()
	args := make([]SnapshotTranscriptMtimeArgs, len(fake.transcriptMtimeArgsForCall))
	copy(args, fake.transcriptMtimeArgsForCall)
	return args
}

func (fake *Snapshot) TranscriptMtimeReturns(result1 *time.DateTime) {
	fake.transcriptMtimeMutex.Lock()
	defer fake.transcriptMtimeMutex.Unlock()
	fake.TranscriptMtimeStub = nil
	fake.transcriptMtimeReturns = struct {
		result1 *time.DateTime
	}{result1}
}

func (fake *Snapshot) TranscriptMtimeReturnsOnCall(i int, result1 *time.DateTime) {
	fake.transcriptMtimeMutex.Lock()
	defer fake.transcriptMtimeMutex.Unlock()
	fake.TranscriptMtimeStub = nil
	if fake.transcriptMtimeReturnsOnCall == nil {
		fake.transcriptMtimeReturnsOnCall = make(map[int]struct {
			result1 *time.DateTime
		})
	}
	fake.transcriptMtimeReturnsOnCall[i] = struct {
		result1 *time.DateTime
	}{result1}
}

func (fake *Snapshot) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Snapshot) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *Snapshot) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sessionsnapshot.Snapshot = new(Snapshot)
