// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-ui/pkg/queue"
)

type Queue struct {
	ConsumeStub        func(context.Context) error
	consumeMutex       sync.RWMutex
	consumeArgsForCall []QueueConsumeArgs
	consumeReturns     struct {
		result1 error
	}
	consumeReturnsOnCall map[int]struct {
		result1 error
	}
	DoneStub        func(string) <-chan struct{}
	doneMutex       sync.RWMutex
	doneArgsForCall []QueueDoneArgs
	doneReturns     struct {
		result1 <-chan struct{}
	}
	doneReturnsOnCall map[int]struct {
		result1 <-chan struct{}
	}
	EnqueueStub        func(context.Context, queue.Write) error
	enqueueMutex       sync.RWMutex
	enqueueArgsForCall []QueueEnqueueArgs
	enqueueReturns     struct {
		result1 error
	}
	enqueueReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// QueueConsumeArgs holds the arguments of one call to Consume.
type QueueConsumeArgs struct {
	Arg1 context.Context
}

// QueueDoneArgs holds the arguments of one call to Done.
type QueueDoneArgs struct {
	Arg1 string
}

// QueueEnqueueArgs holds the arguments of one call to Enqueue.
type QueueEnqueueArgs struct {
	Arg1 context.Context
	Arg2 queue.Write
}

func (fake *Queue) Consume(arg1 context.Context) error {
	fake.consumeMutex.Lock()
	ret, specificReturn := fake.consumeReturnsOnCall[len(fake.consumeArgsForCall)]
	fake.consumeArgsForCall = append(fake.consumeArgsForCall, QueueConsumeArgs{arg1})
	stub := fake.ConsumeStub
	fakeReturns := fake.consumeReturns
	fake.recordInvocation("Consume", []interface{}{arg1})
	fake.consumeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Queue) ConsumeCallCount() int {
	fake.consumeMutex.RLock()
	defer fake.consumeMutex.RUnlock()
	return len(fake.consumeArgsForCall)
}

func (fake *Queue) ConsumeCalls(stub func(context.Context) error) {
	fake.consumeMutex.Lock()
	defer fake.consumeMutex.Unlock()
	fake.ConsumeStub = stub
}

func (fake *Queue) ConsumeArgsForCall(i int) context.Context {
	fake.consumeMutex.RLock()
	defer fake.consumeMutex.RUnlock()
	argsForCall := fake.consumeArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *Queue) ConsumeArgs() []QueueConsumeArgs {
	fake.consumeMutex.RLock()
	defer fake.consumeMutex.RUnlock()
	args := make([]QueueConsumeArgs, len(fake.consumeArgsForCall))
	copy(args, fake.consumeArgsForCall)
	return args
}

func (fake *Queue) ConsumeReturns(result1 error) {
	fake.consumeMutex.Lock()
	defer fake.consumeMutex.Unlock()
	fake.ConsumeStub = nil
	fake.consumeReturns = struct {
		result1 error
	}{result1}
}

func (fake *Queue) ConsumeReturnsOnCall(i int, result1 error) {
	fake.consumeMutex.Lock()
	defer fake.consumeMutex.Unlock()
	fake.ConsumeStub = nil
	if fake.consumeReturnsOnCall == nil {
		fake.consumeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.consumeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Queue) Done(arg1 string) <-chan struct{} {
	fake.doneMutex.Lock()
	ret, specificReturn := fake.doneReturnsOnCall[len(fake.doneArgsForCall)]
	fake.doneArgsForCall = append(fake.doneArgsForCall, QueueDoneArgs{arg1})
	stub := fake.DoneStub
	fakeReturns := fake.doneReturns
	fake.recordInvocation("Done", []interface{}{arg1})
	fake.doneMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Queue) DoneCallCount() int {
	fake.doneMutex.RLock()
	defer fake.doneMutex.RUnlock()
	return len(fake.doneArgsForCall)
}

func (fake *Queue) DoneCalls(stub func(string) <-chan struct{}) {
	fake.doneMutex.Lock()
	defer fake.doneMutex.Unlock()
	fake.DoneStub = stub
}

func (fake *Queue) DoneArgsForCall(i int) string {
	fake.doneMutex.RLock()
	defer fake.doneMutex.RUnlock()
	argsForCall := fake.doneArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *Queue) DoneArgs() []QueueDoneArgs {
	fake.doneMutex.RLock()
	defer fake.doneMutex.RUnlock()
	args := make([]QueueDoneArgs, len(fake.doneArgsForCall))
	copy(args, fake.doneArgsForCall)
	return args
}

func (fake *Queue) DoneReturns(result1 <-chan struct{}) {
	fake.doneMutex.Lock()
	defer fake.doneMutex.Unlock()
	fake.DoneStub = nil
	fake.doneReturns = struct {
		result1 <-chan struct{}
	}{result1}
}

func (fake *Queue) DoneReturnsOnCall(i int, result1 <-chan struct{}) {
	fake.doneMutex.Lock()
	defer fake.doneMutex.Unlock()
	fake.DoneStub = nil
	if fake.doneReturnsOnCall == nil {
		fake.doneReturnsOnCall = make(map[int]struct {
			result1 <-chan struct{}
		})
	}
	fake.doneReturnsOnCall[i] = struct {
		result1 <-chan struct{}
	}{result1}
}

func (fake *Queue) Enqueue(arg1 context.Context, arg2 queue.Write) error {
	fake.enqueueMutex.Lock()
	ret, specificReturn := fake.enqueueReturnsOnCall[len(fake.enqueueArgsForCall)]
	fake.enqueueArgsForCall = append(fake.enqueueArgsForCall, QueueEnqueueArgs{arg1, arg2})
	stub := fake.EnqueueStub
	fakeReturns := fake.enqueueReturns
	fake.recordInvocation("Enqueue", []interface{}{arg1, arg2})
	fake.enqueueMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Queue) EnqueueCallCount() int {
	fake.enqueueMutex.RLock()
	defer fake.enqueueMutex.RUnlock()
	return len(fake.enqueueArgsForCall)
}

func (fake *Queue) EnqueueCalls(stub func(context.Context, queue.Write) error) {
	fake.enqueueMutex.Lock()
	defer fake.enqueueMutex.Unlock()
	fake.EnqueueStub = stub
}

func (fake *Queue) EnqueueArgsForCall(i int) (context.Context, queue.Write) {
	fake.enqueueMutex.RLock()
	defer fake.enqueueMutex.RUnlock()
	argsForCall := fake.enqueueArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *Queue) EnqueueArgs() []QueueEnqueueArgs {
	fake.enqueueMutex.RLock()
	defer fake.enqueueMutex.RUnlock()
	args := make([]QueueEnqueueArgs, len(fake.enqueueArgsForCall))
	copy(args, fake.enqueueArgsForCall)
	return args
}

func (fake *Queue) EnqueueReturns(result1 error) {
	fake.enqueueMutex.Lock()
	defer fake.enqueueMutex.Unlock()
	fake.EnqueueStub = nil
	fake.enqueueReturns = struct {
		result1 error
	}{result1}
}

func (fake *Queue) EnqueueReturnsOnCall(i int, result1 error) {
	fake.enqueueMutex.Lock()
	defer fake.enqueueMutex.Unlock()
	fake.EnqueueStub = nil
	if fake.enqueueReturnsOnCall == nil {
		fake.enqueueReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.enqueueReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Queue) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Queue) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *Queue) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ queue.Queue = new(Queue)
