// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/vault-ui/pkg/websocket"
)

type WebsocketMetrics struct {
	BroadcastStub        func()
	broadcastMutex       sync.RWMutex
	broadcastArgsForCall []struct {
	}
	ClientConnectedStub        func()
	clientConnectedMutex       sync.RWMutex
	clientConnectedArgsForCall []struct {
	}
	ClientDisconnectedStub        func()
	clientDisconnectedMutex       sync.RWMutex
	clientDisconnectedArgsForCall []struct {
	}
	ClientDroppedStub        func()
	clientDroppedMutex       sync.RWMutex
	clientDroppedArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *WebsocketMetrics) Broadcast() {
	fake.broadcastMutex.Lock()
	fake.broadcastArgsForCall = append(fake.broadcastArgsForCall, struct {
	}{})
	stub := fake.BroadcastStub
	fake.recordInvocation("Broadcast", []interface{}{})
	fake.broadcastMutex.Unlock()
	if stub != nil {
		fake.BroadcastStub()
	}
}

func (fake *WebsocketMetrics) BroadcastCallCount() int {
	fake.broadcastMutex.RLock()
	defer fake.broadcastMutex.RUnlock()
	return len(fake.broadcastArgsForCall)
}

func (fake *WebsocketMetrics) BroadcastCalls(stub func()) {
	fake.broadcastMutex.Lock()
	defer fake.broadcastMutex.Unlock()
	fake.BroadcastStub = stub
}

func (fake *WebsocketMetrics) ClientConnected() {
	fake.clientConnectedMutex.Lock()
	fake.clientConnectedArgsForCall = append(fake.clientConnectedArgsForCall, struct {
	}{})
	stub := fake.ClientConnectedStub
	fake.recordInvocation("ClientConnected", []interface{}{})
	fake.clientConnectedMutex.Unlock()
	if stub != nil {
		fake.ClientConnectedStub()
	}
}

func (fake *WebsocketMetrics) ClientConnectedCallCount() int {
	fake.clientConnectedMutex.RLock()
	defer fake.clientConnectedMutex.RUnlock()
	return len(fake.clientConnectedArgsForCall)
}

func (fake *WebsocketMetrics) ClientConnectedCalls(stub func()) {
	fake.clientConnectedMutex.Lock()
	defer fake.clientConnectedMutex.Unlock()
	fake.ClientConnectedStub = stub
}

func (fake *WebsocketMetrics) ClientDisconnected() {
	fake.clientDisconnectedMutex.Lock()
	fake.clientDisconnectedArgsForCall = append(fake.clientDisconnectedArgsForCall, struct {
	}{})
	stub := fake.ClientDisconnectedStub
	fake.recordInvocation("ClientDisconnected", []interface{}{})
	fake.clientDisconnectedMutex.Unlock()
	if stub != nil {
		fake.ClientDisconnectedStub()
	}
}

func (fake *WebsocketMetrics) ClientDisconnectedCallCount() int {
	fake.clientDisconnectedMutex.RLock()
	defer fake.clientDisconnectedMutex.RUnlock()
	return len(fake.clientDisconnectedArgsForCall)
}

func (fake *WebsocketMetrics) ClientDisconnectedCalls(stub func()) {
	fake.clientDisconnectedMutex.Lock()
	defer fake.clientDisconnectedMutex.Unlock()
	fake.ClientDisconnectedStub = stub
}

func (fake *WebsocketMetrics) ClientDropped() {
	fake.clientDroppedMutex.Lock()
	fake.clientDroppedArgsForCall = append(fake.clientDroppedArgsForCall, struct {
	}{})
	stub := fake.ClientDroppedStub
	fake.recordInvocation("ClientDropped", []interface{}{})
	fake.clientDroppedMutex.Unlock()
	if stub != nil {
		fake.ClientDroppedStub()
	}
}

func (fake *WebsocketMetrics) ClientDroppedCallCount() int {
	fake.clientDroppedMutex.RLock()
	defer fake.clientDroppedMutex.RUnlock()
	return len(fake.clientDroppedArgsForCall)
}

func (fake *WebsocketMetrics) ClientDroppedCalls(stub func()) {
	fake.clientDroppedMutex.Lock()
	defer fake.clientDroppedMutex.Unlock()
	fake.ClientDroppedStub = stub
}

func (fake *WebsocketMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *WebsocketMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ websocket.Metrics = new(WebsocketMetrics)
