// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-ui/pkg/websocket"
)

type WebsocketConnectionManager struct {
	BroadcastStub        func([]byte)
	broadcastMutex       sync.RWMutex
	broadcastArgsForCall []WebsocketConnectionManagerBroadcastArgs
	ConnectStub          func(websocket.Conn) (*websocket.Client, error)
	connectMutex         sync.RWMutex
	connectArgsForCall   []WebsocketConnectionManagerConnectArgs
	connectReturns       struct {
		result1 *websocket.Client
		result2 error
	}
	connectReturnsOnCall map[int]struct {
		result1 *websocket.Client
		result2 error
	}
	CountStub        func() int
	countMutex       sync.RWMutex
	countArgsForCall []struct{}
	countReturns     struct {
		result1 int
	}
	countReturnsOnCall map[int]struct {
		result1 int
	}
	DisconnectStub        func(*websocket.Client)
	disconnectMutex       sync.RWMutex
	disconnectArgsForCall []WebsocketConnectionManagerDisconnectArgs
	PumpStub              func(context.Context, *websocket.Client) error
	pumpMutex             sync.RWMutex
	pumpArgsForCall       []WebsocketConnectionManagerPumpArgs
	pumpReturns           struct {
		result1 error
	}
	pumpReturnsOnCall map[int]struct {
		result1 error
	}
	SendStub         func(*websocket.Client, []byte)
	sendMutex        sync.RWMutex
	sendArgsForCall  []WebsocketConnectionManagerSendArgs
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// WebsocketConnectionManagerBroadcastArgs holds the arguments of one call to Broadcast.
type WebsocketConnectionManagerBroadcastArgs struct {
	Arg1 []byte
}

// WebsocketConnectionManagerConnectArgs holds the arguments of one call to Connect.
type WebsocketConnectionManagerConnectArgs struct {
	Arg1 websocket.Conn
}

// WebsocketConnectionManagerDisconnectArgs holds the arguments of one call to Disconnect.
type WebsocketConnectionManagerDisconnectArgs struct {
	Arg1 *websocket.Client
}

// WebsocketConnectionManagerPumpArgs holds the arguments of one call to Pump.
type WebsocketConnectionManagerPumpArgs struct {
	Arg1 context.Context
	Arg2 *websocket.Client
}

// WebsocketConnectionManagerSendArgs holds the arguments of one call to Send.
type WebsocketConnectionManagerSendArgs struct {
	Arg1 *websocket.Client
	Arg2 []byte
}

func (fake *WebsocketConnectionManager) Broadcast(arg1 []byte) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.broadcastMutex.Lock()
	fake.broadcastArgsForCall = append(fake.broadcastArgsForCall, WebsocketConnectionManagerBroadcastArgs{arg1Copy})
	stub := fake.BroadcastStub
	fake.recordInvocation("Broadcast", []interface{}{arg1Copy})
	fake.broadcastMutex.Unlock()
	if stub != nil {
		stub(arg1)
	}
}

func (fake *WebsocketConnectionManager) BroadcastCallCount() int {
	fake.broadcastMutex.RLock()
	defer fake.broadcastMutex.RUnlock()
	return len(fake.broadcastArgsForCall)
}

func (fake *WebsocketConnectionManager) BroadcastCalls(stub func([]byte)) {
	fake.broadcastMutex.Lock()
	defer fake.broadcastMutex.Unlock()
	fake.BroadcastStub = stub
}

func (fake *WebsocketConnectionManager) BroadcastArgsForCall(i int) []byte {
	fake.broadcastMutex.RLock()
	defer fake.broadcastMutex.RUnlock()
	argsForCall := fake.broadcastArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *WebsocketConnectionManager) BroadcastArgs() []WebsocketConnectionManagerBroadcastArgs {
	fake.broadcastMutex.RLock()
	defer fake.broadcastMutex.RUnlock()
	args := make([]WebsocketConnectionManagerBroadcastArgs, len(fake.broadcastArgsForCall))
	copy(args, fake.broadcastArgsForCall)
	return args
}

func (fake *WebsocketConnectionManager) Connect(arg1 websocket.Conn) (*websocket.Client, error) {
	fake.connectMutex.Lock()
	ret, specificReturn := fake.connectReturnsOnCall[len(fake.connectArgsForCall)]
	fake.connectArgsForCall = append(fake.connectArgsForCall, WebsocketConnectionManagerConnectArgs{arg1})
	stub := fake.ConnectStub
	fakeReturns := fake.connectReturns
	fake.recordInvocation("Connect", []interface{}{arg1})
	fake.connectMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *WebsocketConnectionManager) ConnectCallCount() int {
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	return len(fake.connectArgsForCall)
}

func (fake *WebsocketConnectionManager) ConnectCalls(stub func(websocket.Conn) (*websocket.Client, error)) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = stub
}

func (fake *WebsocketConnectionManager) ConnectArgsForCall(i int) websocket.Conn {
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	argsForCall := fake.connectArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *WebsocketConnectionManager) ConnectArgs() []WebsocketConnectionManagerConnectArgs {
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	args := make([]WebsocketConnectionManagerConnectArgs, len(fake.connectArgsForCall))
	copy(args, fake.connectArgsForCall)
	return args
}

func (fake *WebsocketConnectionManager) ConnectReturns(result1 *websocket.Client, result2 error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = nil
	fake.connectReturns = struct {
		result1 *websocket.Client
		result2 error
	}{result1, result2}
}

func (fake *WebsocketConnectionManager) ConnectReturnsOnCall(i int, result1 *websocket.Client, result2 error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = nil
	if fake.connectReturnsOnCall == nil {
		fake.connectReturnsOnCall = make(map[int]struct {
			result1 *websocket.Client
			result2 error
		})
	}
	fake.connectReturnsOnCall[i] = struct {
		result1 *websocket.Client
		result2 error
	}{result1, result2}
}

func (fake *WebsocketConnectionManager) Count() int {
	fake.countMutex.Lock()
	ret, specificReturn := fake.countReturnsOnCall[len(fake.countArgsForCall)]
	fake.countArgsForCall = append(fake.countArgsForCall, struct{}{})
	stub := fake.CountStub
	fakeReturns := fake.countReturns
	fake.recordInvocation("Count", []interface{}{})
	fake.countMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *WebsocketConnectionManager) CountCallCount() int {
	fake.countMutex.RLock()
	defer fake.countMutex.RUnlock()
	return len(fake.countArgsForCall)
}

func (fake *WebsocketConnectionManager) CountCalls(stub func() int) {
	fake.countMutex.Lock()
	defer fake.countMutex.Unlock()
	fake.CountStub = stub
}

func (fake *WebsocketConnectionManager) CountReturns(result1 int) {
	fake.countMutex.Lock()
	defer fake.countMutex.Unlock()
	fake.CountStub = nil
	fake.countReturns = struct {
		result1 int
	}{result1}
}

func (fake *WebsocketConnectionManager) CountReturnsOnCall(i int, result1 int) {
	fake.countMutex.Lock()
	defer fake.countMutex.Unlock()
	fake.CountStub = nil
	if fake.countReturnsOnCall == nil {
		fake.countReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.countReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *WebsocketConnectionManager) Disconnect(arg1 *websocket.Client) {
	fake.disconnectMutex.Lock()
	fake.disconnectArgsForCall = append(fake.disconnectArgsForCall, WebsocketConnectionManagerDisconnectArgs{arg1})
	stub := fake.DisconnectStub
	fake.recordInvocation("Disconnect", []interface{}{arg1})
	fake.disconnectMutex.Unlock()
	if stub != nil {
		stub(arg1)
	}
}

func (fake *WebsocketConnectionManager) DisconnectCallCount() int {
	fake.disconnectMutex.RLock()
	defer fake.disconnectMutex.RUnlock()
	return len(fake.disconnectArgsForCall)
}

func (fake *WebsocketConnectionManager) DisconnectCalls(stub func(*websocket.Client)) {
	fake.disconnectMutex.Lock()
	defer fake.disconnectMutex.Unlock()
	fake.DisconnectStub = stub
}

func (fake *WebsocketConnectionManager) DisconnectArgsForCall(i int) *websocket.Client {
	fake.disconnectMutex.RLock()
	defer fake.disconnectMutex.RUnlock()
	argsForCall := fake.disconnectArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *WebsocketConnectionManager) DisconnectArgs() []WebsocketConnectionManagerDisconnectArgs {
	fake.disconnectMutex.RLock()
	defer fake.disconnectMutex.RUnlock()
	args := make([]WebsocketConnectionManagerDisconnectArgs, len(fake.disconnectArgsForCall))
	copy(args, fake.disconnectArgsForCall)
	return args
}

func (fake *WebsocketConnectionManager) Pump(arg1 context.Context, arg2 *websocket.Client) error {
	fake.pumpMutex.Lock()
	ret, specificReturn := fake.pumpReturnsOnCall[len(fake.pumpArgsForCall)]
	fake.pumpArgsForCall = append(fake.pumpArgsForCall, WebsocketConnectionManagerPumpArgs{arg1, arg2})
	stub := fake.PumpStub
	fakeReturns := fake.pumpReturns
	fake.recordInvocation("Pump", []interface{}{arg1, arg2})
	fake.pumpMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *WebsocketConnectionManager) PumpCallCount() int {
	fake.pumpMutex.RLock()
	defer fake.pumpMutex.RUnlock()
	return len(fake.pumpArgsForCall)
}

func (fake *WebsocketConnectionManager) PumpCalls(stub func(context.Context, *websocket.Client) error) {
	fake.pumpMutex.Lock()
	defer fake.pumpMutex.Unlock()
	fake.PumpStub = stub
}

func (fake *WebsocketConnectionManager) PumpArgsForCall(i int) (context.Context, *websocket.Client) {
	fake.pumpMutex.RLock()
	defer fake.pumpMutex.RUnlock()
	argsForCall := fake.pumpArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *WebsocketConnectionManager) PumpArgs() []WebsocketConnectionManagerPumpArgs {
	fake.pumpMutex.RLock()
	defer fake.pumpMutex.RUnlock()
	args := make([]WebsocketConnectionManagerPumpArgs, len(fake.pumpArgsForCall))
	copy(args, fake.pumpArgsForCall)
	return args
}

func (fake *WebsocketConnectionManager) PumpReturns(result1 error) {
	fake.pumpMutex.Lock()
	defer fake.pumpMutex.Unlock()
	fake.PumpStub = nil
	fake.pumpReturns = struct {
		result1 error
	}{result1}
}

func (fake *WebsocketConnectionManager) PumpReturnsOnCall(i int, result1 error) {
	fake.pumpMutex.Lock()
	defer fake.pumpMutex.Unlock()
	fake.PumpStub = nil
	if fake.pumpReturnsOnCall == nil {
		fake.pumpReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pumpReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *WebsocketConnectionManager) Send(arg1 *websocket.Client, arg2 []byte) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.sendMutex.Lock()
	fake.sendArgsForCall = append(fake.sendArgsForCall, WebsocketConnectionManagerSendArgs{arg1, arg2Copy})
	stub := fake.SendStub
	fake.recordInvocation("Send", []interface{}{arg1, arg2Copy})
	fake.sendMutex.Unlock()
	if stub != nil {
		stub(arg1, arg2)
	}
}

func (fake *WebsocketConnectionManager) SendCallCount() int {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	return len(fake.sendArgsForCall)
}

func (fake *WebsocketConnectionManager) SendCalls(stub func(*websocket.Client, []byte)) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = stub
}

func (fake *WebsocketConnectionManager) SendArgsForCall(i int) (*websocket.Client, []byte) {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	argsForCall := fake.sendArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *WebsocketConnectionManager) SendArgs() []WebsocketConnectionManagerSendArgs {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	args := make([]WebsocketConnectionManagerSendArgs, len(fake.sendArgsForCall))
	copy(args, fake.sendArgsForCall)
	return args
}

func (fake *WebsocketConnectionManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *WebsocketConnectionManager) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *WebsocketConnectionManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ websocket.ConnectionManager = new(WebsocketConnectionManager)
