// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-ui/pkg/pageindex"
)

type PageReader struct {
	ReadPageStub        func(context.Context, string, string, string) (*domain.Page, pageindex.FileFingerprint, error)
	readPageMutex       sync.RWMutex
	readPageArgsForCall []PageReaderReadPageArgs
	readPageReturns     struct {
		result1 *domain.Page
		result2 pageindex.FileFingerprint
		result3 error
	}
	readPageReturnsOnCall map[int]struct {
		result1 *domain.Page
		result2 pageindex.FileFingerprint
		result3 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// PageReaderReadPageArgs holds the arguments of one call to ReadPage.
type PageReaderReadPageArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
	Arg4 string
}

func (fake *PageReader) ReadPage(arg1 context.Context, arg2 string, arg3 string, arg4 string) (*domain.Page, pageindex.FileFingerprint, error) {
	fake.readPageMutex.Lock()
	ret, specificReturn := fake.readPageReturnsOnCall[len(fake.readPageArgsForCall)]
	fake.readPageArgsForCall = append(fake.readPageArgsForCall, PageReaderReadPageArgs{arg1, arg2, arg3, arg4})
	stub := fake.ReadPageStub
	fakeReturns := fake.readPageReturns
	fake.recordInvocation("ReadPage", []interface{}{arg1, arg2, arg3, arg4})
	fake.readPageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *PageReader) ReadPageCallCount() int {
	fake.readPageMutex.RLock()
	defer fake.readPageMutex.RUnlock()
	return len(fake.readPageArgsForCall)
}

func (fake *PageReader) ReadPageCalls(stub func(context.Context, string, string, string) (*domain.Page, pageindex.FileFingerprint, error)) {
	fake.readPageMutex.Lock()
	defer fake.readPageMutex.Unlock()
	fake.ReadPageStub = stub
}

func (fake *PageReader) ReadPageArgsForCall(i int) (context.Context, string, string, string) {
	fake.readPageMutex.RLock()
	defer fake.readPageMutex.RUnlock()
	argsForCall := fake.readPageArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *PageReader) ReadPageArgs() []PageReaderReadPageArgs {
	fake.readPageMutex.RLock()
	defer fake.readPageMutex.RUnlock()
	args := make([]PageReaderReadPageArgs, len(fake.readPageArgsForCall))
	copy(args, fake.readPageArgsForCall)
	return args
}

func (fake *PageReader) ReadPageReturns(result1 *domain.Page, result2 pageindex.FileFingerprint, result3 error) {
	fake.readPageMutex.Lock()
	defer fake.readPageMutex.Unlock()
	fake.ReadPageStub = nil
	fake.readPageReturns = struct {
		result1 *domain.Page
		result2 pageindex.FileFingerprint
		result3 error
	}{result1, result2, result3}
}

func (fake *PageReader) ReadPageReturnsOnCall(i int, result1 *domain.Page, result2 pageindex.FileFingerprint, result3 error) {
	fake.readPageMutex.Lock()
	defer fake.readPageMutex.Unlock()
	fake.ReadPageStub = nil
	if fake.readPageReturnsOnCall == nil {
		fake.readPageReturnsOnCall = make(map[int]struct {
			result1 *domain.Page
			result2 pageindex.FileFingerprint
			result3 error
		})
	}
	fake.readPageReturnsOnCall[i] = struct {
		result1 *domain.Page
		result2 pageindex.FileFingerprint
		result3 error
	}{result1, result2, result3}
}

func (fake *PageReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PageReader) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *PageReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pageindex.PageReader = new(PageReader)
