// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-ui/pkg/pageindex"
)

type PageIndex struct {
	BuildStub        func(context.Context, []pageindex.Key) error
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
		arg1 context.Context
		arg2 []pageindex.Key
	}
	buildReturns struct {
		result1 error
	}
	buildReturnsOnCall map[int]struct {
		result1 error
	}
	ForceReloadStub        func()
	forceReloadMutex       sync.RWMutex
	forceReloadArgsForCall []struct {
	}
	ListPagesStub        func(context.Context, string, string) ([]*domain.Page, error)
	listPagesMutex       sync.RWMutex
	listPagesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	listPagesReturns struct {
		result1 []*domain.Page
		result2 error
	}
	listPagesReturnsOnCall map[int]struct {
		result1 []*domain.Page
		result2 error
	}
	MarkDirtyStub        func(...pageindex.Key)
	markDirtyMutex       sync.RWMutex
	markDirtyArgsForCall []struct {
		arg1 []pageindex.Key
	}
	MarkFileDirtyStub        func(pageindex.Key, string)
	markFileDirtyMutex       sync.RWMutex
	markFileDirtyArgsForCall []struct {
		arg1 pageindex.Key
		arg2 string
	}
	ReadPageStub        func(context.Context, string, string, string) (*domain.Page, error)
	readPageMutex       sync.RWMutex
	readPageArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	readPageReturns struct {
		result1 *domain.Page
		result2 error
	}
	readPageReturnsOnCall map[int]struct {
		result1 *domain.Page
		result2 error
	}
	RefreshStub        func(context.Context, pageindex.Key) error
	refreshMutex       sync.RWMutex
	refreshArgsForCall []struct {
		arg1 context.Context
		arg2 pageindex.Key
	}
	refreshReturns struct {
		result1 error
	}
	refreshReturnsOnCall map[int]struct {
		result1 error
	}
	RefreshFileStub        func(context.Context, pageindex.Key, string) error
	refreshFileMutex       sync.RWMutex
	refreshFileArgsForCall []struct {
		arg1 context.Context
		arg2 pageindex.Key
		arg3 string
	}
	refreshFileReturns struct {
		result1 error
	}
	refreshFileReturnsOnCall map[int]struct {
		result1 error
	}
	RescanStub        func(context.Context) error
	rescanMutex       sync.RWMutex
	rescanArgsForCall []struct {
		arg1 context.Context
	}
	rescanReturns struct {
		result1 error
	}
	rescanReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *PageIndex) Build(arg1 context.Context, arg2 []pageindex.Key) error {
	var arg2Copy []pageindex.Key
	if arg2 != nil {
		arg2Copy = make([]pageindex.Key, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.buildMutex.Lock()
	ret, specificReturn := fake.buildReturnsOnCall[len(fake.buildArgsForCall)]
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
		arg1 context.Context
		arg2 []pageindex.Key
	}{arg1, arg2Copy})
	stub := fake.BuildStub
	fakeReturns := fake.buildReturns
	fake.recordInvocation("Build", []interface{}{arg1, arg2Copy})
	fake.buildMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *PageIndex) BuildCalls(stub func(context.Context, []pageindex.Key) error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = stub
}

func (fake *PageIndex) BuildArgsForCall(i int) (context.Context, []pageindex.Key) {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	argsForCall := fake.buildArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PageIndex) BuildReturns(result1 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) BuildReturnsOnCall(i int, result1 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	if fake.buildReturnsOnCall == nil {
		fake.buildReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.buildReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) ForceReload() {
	fake.forceReloadMutex.Lock()
	fake.forceReloadArgsForCall = append(fake.forceReloadArgsForCall, struct {
	}{})
	stub := fake.ForceReloadStub
	fake.recordInvocation("ForceReload", []interface{}{})
	fake.forceReloadMutex.Unlock()
	if stub != nil {
		fake.ForceReloadStub()
	}
}

func (fake *PageIndex) ForceReloadCallCount() int {
	fake.forceReloadMutex.RLock()
	defer fake.forceReloadMutex.RUnlock()
	return len(fake.forceReloadArgsForCall)
}

func (fake *PageIndex) ForceReloadCalls(stub func()) {
	fake.forceReloadMutex.Lock()
	defer fake.forceReloadMutex.Unlock()
	fake.ForceReloadStub = stub
}

func (fake *PageIndex) ListPages(arg1 context.Context, arg2 string, arg3 string) ([]*domain.Page, error) {
	fake.listPagesMutex.Lock()
	ret, specificReturn := fake.listPagesReturnsOnCall[len(fake.listPagesArgsForCall)]
	fake.listPagesArgsForCall = append(fake.listPagesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ListPagesStub
	fakeReturns := fake.listPagesReturns
	fake.recordInvocation("ListPages", []interface{}{arg1, arg2, arg3})
	fake.listPagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PageIndex) ListPagesCallCount() int {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	return len(fake.listPagesArgsForCall)
}

func (fake *PageIndex) ListPagesCalls(stub func(context.Context, string, string) ([]*domain.Page, error)) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = stub
}

func (fake *PageIndex) ListPagesArgsForCall(i int) (context.Context, string, string) {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	argsForCall := fake.listPagesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *PageIndex) ListPagesReturns(result1 []*domain.Page, result2 error) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = nil
	fake.listPagesReturns = struct {
		result1 []*domain.Page
		result2 error
	}{result1, result2}
}

func (fake *PageIndex) ListPagesReturnsOnCall(i int, result1 []*domain.Page, result2 error) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = nil
	if fake.listPagesReturnsOnCall == nil {
		fake.listPagesReturnsOnCall = make(map[int]struct {
			result1 []*domain.Page
			result2 error
		})
	}
	fake.listPagesReturnsOnCall[i] = struct {
		result1 []*domain.Page
		result2 error
	}{result1, result2}
}

func (fake *PageIndex) MarkDirty(arg1 ...pageindex.Key) {
	fake.markDirtyMutex.Lock()
	fake.markDirtyArgsForCall = append(fake.markDirtyArgsForCall, struct {
		arg1 []pageindex.Key
	}{arg1})
	stub := fake.MarkDirtyStub
	fake.recordInvocation("MarkDirty", []interface{}{arg1})
	fake.markDirtyMutex.Unlock()
	if stub != nil {
		fake.MarkDirtyStub(arg1...)
	}
}

func (fake *PageIndex) MarkDirtyCallCount() int {
	fake.markDirtyMutex.RLock()
	defer fake.markDirtyMutex.RUnlock()
	return len(fake.markDirtyArgsForCall)
}

func (fake *PageIndex) MarkDirtyCalls(stub func(...pageindex.Key)) {
	fake.markDirtyMutex.Lock()
	defer fake.markDirtyMutex.Unlock()
	fake.MarkDirtyStub = stub
}

func (fake *PageIndex) MarkDirtyArgsForCall(i int) []pageindex.Key {
	fake.markDirtyMutex.RLock()
	defer fake.markDirtyMutex.RUnlock()
	argsForCall := fake.markDirtyArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PageIndex) MarkFileDirty(arg1 pageindex.Key, arg2 string) {
	fake.markFileDirtyMutex.Lock()
	fake.markFileDirtyArgsForCall = append(fake.markFileDirtyArgsForCall, struct {
		arg1 pageindex.Key
		arg2 string
	}{arg1, arg2})
	stub := fake.MarkFileDirtyStub
	fake.recordInvocation("MarkFileDirty", []interface{}{arg1, arg2})
	fake.markFileDirtyMutex.Unlock()
	if stub != nil {
		fake.MarkFileDirtyStub(arg1, arg2)
	}
}

func (fake *PageIndex) MarkFileDirtyCallCount() int {
	fake.markFileDirtyMutex.RLock()
	defer fake.markFileDirtyMutex.RUnlock()
	return len(fake.markFileDirtyArgsForCall)
}

func (fake *PageIndex) MarkFileDirtyCalls(stub func(pageindex.Key, string)) {
	fake.markFileDirtyMutex.Lock()
	defer fake.markFileDirtyMutex.Unlock()
	fake.MarkFileDirtyStub = stub
}

func (fake *PageIndex) MarkFileDirtyArgsForCall(i int) (pageindex.Key, string) {
	fake.markFileDirtyMutex.RLock()
	defer fake.markFileDirtyMutex.RUnlock()
	argsForCall := fake.markFileDirtyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PageIndex) ReadPage(arg1 context.Context, arg2 string, arg3 string, arg4 string) (*domain.Page, error) {
	fake.readPageMutex.Lock()
	ret, specificReturn := fake.readPageReturnsOnCall[len(fake.readPageArgsForCall)]
	fake.readPageArgsForCall = append(fake.readPageArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.ReadPageStub
	fakeReturns := fake.readPageReturns
	fake.recordInvocation("ReadPage", []interface{}{arg1, arg2, arg3, arg4})
	fake.readPageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PageIndex) ReadPageCallCount() int {
	fake.readPageMutex.RLock()
	defer fake.readPageMutex.RUnlock()
	return len(fake.readPageArgsForCall)
}

func (fake *PageIndex) ReadPageCalls(stub func(context.Context, string, string, string) (*domain.Page, error)) {
	fake.readPageMutex.Lock()
	defer fake.readPageMutex.Unlock()
	fake.ReadPageStub = stub
}

func (fake *PageIndex) ReadPageArgsForCall(i int) (context.Context, string, string, string) {
	fake.readPageMutex.RLock()
	defer fake.readPageMutex.RUnlock()
	argsForCall := fake.readPageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *PageIndex) ReadPageReturns(result1 *domain.Page, result2 error) {
	fake.readPageMutex.Lock()
	defer fake.readPageMutex.Unlock()
	fake.ReadPageStub = nil
	fake.readPageReturns = struct {
		result1 *domain.Page
		result2 error
	}{result1, result2}
}

func (fake *PageIndex) ReadPageReturnsOnCall(i int, result1 *domain.Page, result2 error) {
	fake.readPageMutex.Lock()
	defer fake.readPageMutex.Unlock()
	fake.ReadPageStub = nil
	if fake.readPageReturnsOnCall == nil {
		fake.readPageReturnsOnCall = make(map[int]struct {
			result1 *domain.Page
			result2 error
		})
	}
	fake.readPageReturnsOnCall[i] = struct {
		result1 *domain.Page
		result2 error
	}{result1, result2}
}

func (fake *PageIndex) Refresh(arg1 context.Context, arg2 pageindex.Key) error {
	fake.refreshMutex.Lock()
	ret, specificReturn := fake.refreshReturnsOnCall[len(fake.refreshArgsForCall)]
	fake.refreshArgsForCall = append(fake.refreshArgsForCall, struct {
		arg1 context.Context
		arg2 pageindex.Key
	}{arg1, arg2})
	stub := fake.RefreshStub
	fakeReturns := fake.refreshReturns
	fake.recordInvocation("Refresh", []interface{}{arg1, arg2})
	fake.refreshMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) RefreshCallCount() int {
	fake.refreshMutex.RLock()
	defer fake.refreshMutex.RUnlock()
	return len(fake.refreshArgsForCall)
}

func (fake *PageIndex) RefreshCalls(stub func(context.Context, pageindex.Key) error) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = stub
}

func (fake *PageIndex) RefreshArgsForCall(i int) (context.Context, pageindex.Key) {
	fake.refreshMutex.RLock()
	defer fake.refreshMutex.RUnlock()
	argsForCall := fake.refreshArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *PageIndex) RefreshReturns(result1 error) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = nil
	fake.refreshReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) RefreshReturnsOnCall(i int, result1 error) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = nil
	if fake.refreshReturnsOnCall == nil {
		fake.refreshReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.refreshReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) RefreshFile(arg1 context.Context, arg2 pageindex.Key, arg3 string) error {
	fake.refreshFileMutex.Lock()
	ret, specificReturn := fake.refreshFileReturnsOnCall[len(fake.refreshFileArgsForCall)]
	fake.refreshFileArgsForCall = append(fake.refreshFileArgsForCall, struct {
		arg1 context.Context
		arg2 pageindex.Key
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.RefreshFileStub
	fakeReturns := fake.refreshFileReturns
	fake.recordInvocation("RefreshFile", []interface{}{arg1, arg2, arg3})
	fake.refreshFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) RefreshFileCallCount() int {
	fake.refreshFileMutex.RLock()
	defer fake.refreshFileMutex.RUnlock()
	return len(fake.refreshFileArgsForCall)
}

func (fake *PageIndex) RefreshFileCalls(stub func(context.Context, pageindex.Key, string) error) {
	fake.refreshFileMutex.Lock()
	defer fake.refreshFileMutex.Unlock()
	fake.RefreshFileStub = stub
}

func (fake *PageIndex) RefreshFileArgsForCall(i int) (context.Context, pageindex.Key, string) {
	fake.refreshFileMutex.RLock()
	defer fake.refreshFileMutex.RUnlock()
	argsForCall := fake.refreshFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *PageIndex) RefreshFileReturns(result1 error) {
	fake.refreshFileMutex.Lock()
	defer fake.refreshFileMutex.Unlock()
	fake.RefreshFileStub = nil
	fake.refreshFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) RefreshFileReturnsOnCall(i int, result1 error) {
	fake.refreshFileMutex.Lock()
	defer fake.refreshFileMutex.Unlock()
	fake.RefreshFileStub = nil
	if fake.refreshFileReturnsOnCall == nil {
		fake.refreshFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.refreshFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) Rescan(arg1 context.Context) error {
	fake.rescanMutex.Lock()
	ret, specificReturn := fake.rescanReturnsOnCall[len(fake.rescanArgsForCall)]
	fake.rescanArgsForCall = append(fake.rescanArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RescanStub
	fakeReturns := fake.rescanReturns
	fake.recordInvocation("Rescan", []interface{}{arg1})
	fake.rescanMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) RescanCallCount() int {
	fake.rescanMutex.RLock()
	defer fake.rescanMutex.RUnlock()
	return len(fake.rescanArgsForCall)
}

func (fake *PageIndex) RescanCalls(stub func(context.Context) error) {
	fake.rescanMutex.Lock()
	defer fake.rescanMutex.Unlock()
	fake.RescanStub = stub
}

func (fake *PageIndex) RescanArgsForCall(i int) context.Context {
	fake.rescanMutex.RLock()
	defer fake.rescanMutex.RUnlock()
	argsForCall := fake.rescanArgsForCall[i]
	return argsForCall.arg1
}

func (fake *PageIndex) RescanReturns(result1 error) {
	fake.rescanMutex.Lock()
	defer fake.rescanMutex.Unlock()
	fake.RescanStub = nil
	fake.rescanReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) RescanReturnsOnCall(i int, result1 error) {
	fake.rescanMutex.Lock()
	defer fake.rescanMutex.Unlock()
	fake.RescanStub = nil
	if fake.rescanReturnsOnCall == nil {
		fake.rescanReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.rescanReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PageIndex) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pageindex.PageIndex = new(PageIndex)
