// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-ui/pkg/pageindex"
)

type PageIndex struct {
	BuildStub        func(context.Context, []pageindex.Key) error
	buildMutex       sync.RWMutex
	buildArgsForCall []PageIndexBuildArgs
	buildReturns     struct {
		result1 error
	}
	buildReturnsOnCall map[int]struct {
		result1 error
	}
	ChangedPagesSinceStub        func(pageindex.Key, uint64) ([]string, bool)
	changedPagesSinceMutex       sync.RWMutex
	changedPagesSinceArgsForCall []PageIndexChangedPagesSinceArgs
	changedPagesSinceReturns     struct {
		result1 []string
		result2 bool
	}
	changedPagesSinceReturnsOnCall map[int]struct {
		result1 []string
		result2 bool
	}
	ForceReloadStub        func()
	forceReloadMutex       sync.RWMutex
	forceReloadArgsForCall []struct{}
	ListPagesStub          func(context.Context, string, string) ([]*domain.Page, error)
	listPagesMutex         sync.RWMutex
	listPagesArgsForCall   []PageIndexListPagesArgs
	listPagesReturns       struct {
		result1 []*domain.Page
		result2 error
	}
	listPagesReturnsOnCall map[int]struct {
		result1 []*domain.Page
		result2 error
	}
	MarkDirtyStub            func(...pageindex.Key)
	markDirtyMutex           sync.RWMutex
	markDirtyArgsForCall     []PageIndexMarkDirtyArgs
	MarkFileDirtyStub        func(pageindex.Key, string)
	markFileDirtyMutex       sync.RWMutex
	markFileDirtyArgsForCall []PageIndexMarkFileDirtyArgs
	ReadPageStub             func(context.Context, string, string, string) (*domain.Page, error)
	readPageMutex            sync.RWMutex
	readPageArgsForCall      []PageIndexReadPageArgs
	readPageReturns          struct {
		result1 *domain.Page
		result2 error
	}
	readPageReturnsOnCall map[int]struct {
		result1 *domain.Page
		result2 error
	}
	RefreshStub        func(context.Context, pageindex.Key) error
	refreshMutex       sync.RWMutex
	refreshArgsForCall []PageIndexRefreshArgs
	refreshReturns     struct {
		result1 error
	}
	refreshReturnsOnCall map[int]struct {
		result1 error
	}
	RefreshFileStub        func(context.Context, pageindex.Key, string) error
	refreshFileMutex       sync.RWMutex
	refreshFileArgsForCall []PageIndexRefreshFileArgs
	refreshFileReturns     struct {
		result1 error
	}
	refreshFileReturnsOnCall map[int]struct {
		result1 error
	}
	RescanStub        func(context.Context) error
	rescanMutex       sync.RWMutex
	rescanArgsForCall []PageIndexRescanArgs
	rescanReturns     struct {
		result1 error
	}
	rescanReturnsOnCall map[int]struct {
		result1 error
	}
	RevisionStub        func(pageindex.Key) uint64
	revisionMutex       sync.RWMutex
	revisionArgsForCall []PageIndexRevisionArgs
	revisionReturns     struct {
		result1 uint64
	}
	revisionReturnsOnCall map[int]struct {
		result1 uint64
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// PageIndexBuildArgs holds the arguments of one call to Build.
type PageIndexBuildArgs struct {
	Arg1 context.Context
	Arg2 []pageindex.Key
}

// PageIndexChangedPagesSinceArgs holds the arguments of one call to ChangedPagesSince.
type PageIndexChangedPagesSinceArgs struct {
	Arg1 pageindex.Key
	Arg2 uint64
}

// PageIndexListPagesArgs holds the arguments of one call to ListPages.
type PageIndexListPagesArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
}

// PageIndexMarkDirtyArgs holds the arguments of one call to MarkDirty.
type PageIndexMarkDirtyArgs struct {
	Arg1 []pageindex.Key
}

// PageIndexMarkFileDirtyArgs holds the arguments of one call to MarkFileDirty.
type PageIndexMarkFileDirtyArgs struct {
	Arg1 pageindex.Key
	Arg2 string
}

// PageIndexReadPageArgs holds the arguments of one call to ReadPage.
type PageIndexReadPageArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
	Arg4 string
}

// PageIndexRefreshArgs holds the arguments of one call to Refresh.
type PageIndexRefreshArgs struct {
	Arg1 context.Context
	Arg2 pageindex.Key
}

// PageIndexRefreshFileArgs holds the arguments of one call to RefreshFile.
type PageIndexRefreshFileArgs struct {
	Arg1 context.Context
	Arg2 pageindex.Key
	Arg3 string
}

// PageIndexRescanArgs holds the arguments of one call to Rescan.
type PageIndexRescanArgs struct {
	Arg1 context.Context
}

// PageIndexRevisionArgs holds the arguments of one call to Revision.
type PageIndexRevisionArgs struct {
	Arg1 pageindex.Key
}

func (fake *PageIndex) Build(arg1 context.Context, arg2 []pageindex.Key) error {
	var arg2Copy []pageindex.Key
	if arg2 != nil {
		arg2Copy = make([]pageindex.Key, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.buildMutex.Lock()
	ret, specificReturn := fake.buildReturnsOnCall[len(fake.buildArgsForCall)]
	fake.buildArgsForCall = append(fake.buildArgsForCall, PageIndexBuildArgs{arg1, arg2Copy})
	stub := fake.BuildStub
	fakeReturns := fake.buildReturns
	fake.recordInvocation("Build", []interface{}{arg1, arg2Copy})
	fake.buildMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *PageIndex) BuildCalls(stub func(context.Context, []pageindex.Key) error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = stub
}

func (fake *PageIndex) BuildArgsForCall(i int) (context.Context, []pageindex.Key) {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	argsForCall := fake.buildArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *PageIndex) BuildArgs() []PageIndexBuildArgs {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	args := make([]PageIndexBuildArgs, len(fake.buildArgsForCall))
	copy(args, fake.buildArgsForCall)
	return args
}

func (fake *PageIndex) BuildReturns(result1 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) BuildReturnsOnCall(i int, result1 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	if fake.buildReturnsOnCall == nil {
		fake.buildReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.buildReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) ChangedPagesSince(arg1 pageindex.Key, arg2 uint64) ([]string, bool) {
	fake.changedPagesSinceMutex.Lock()
	ret, specificReturn := fake.changedPagesSinceReturnsOnCall[len(fake.changedPagesSinceArgsForCall)]
	fake.changedPagesSinceArgsForCall = append(fake.changedPagesSinceArgsForCall, PageIndexChangedPagesSinceArgs{arg1, arg2})
	stub := fake.ChangedPagesSinceStub
	fakeReturns := fake.changedPagesSinceReturns
	fake.recordInvocation("ChangedPagesSince", []interface{}{arg1, arg2})
	fake.changedPagesSinceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PageIndex) ChangedPagesSinceCallCount() int {
	fake.changedPagesSinceMutex.RLock()
	defer fake.changedPagesSinceMutex.RUnlock()
	return len(fake.changedPagesSinceArgsForCall)
}

func (fake *PageIndex) ChangedPagesSinceCalls(stub func(pageindex.Key, uint64) ([]string, bool)) {
	fake.changedPagesSinceMutex.Lock()
	defer fake.changedPagesSinceMutex.Unlock()
	fake.ChangedPagesSinceStub = stub
}

func (fake *PageIndex) ChangedPagesSinceArgsForCall(i int) (pageindex.Key, uint64) {
	fake.changedPagesSinceMutex.RLock()
	defer fake.changedPagesSinceMutex.RUnlock()
	argsForCall := fake.changedPagesSinceArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *PageIndex) ChangedPagesSinceArgs() []PageIndexChangedPagesSinceArgs {
	fake.changedPagesSinceMutex.RLock()
	defer fake.changedPagesSinceMutex.RUnlock()
	args := make([]PageIndexChangedPagesSinceArgs, len(fake.changedPagesSinceArgsForCall))
	copy(args, fake.changedPagesSinceArgsForCall)
	return args
}

func (fake *PageIndex) ChangedPagesSinceReturns(result1 []string, result2 bool) {
	fake.changedPagesSinceMutex.Lock()
	defer fake.changedPagesSinceMutex.Unlock()
	fake.ChangedPagesSinceStub = nil
	fake.changedPagesSinceReturns = struct {
		result1 []string
		result2 bool
	}{result1, result2}
}

func (fake *PageIndex) ChangedPagesSinceReturnsOnCall(i int, result1 []string, result2 bool) {
	fake.changedPagesSinceMutex.Lock()
	defer fake.changedPagesSinceMutex.Unlock()
	fake.ChangedPagesSinceStub = nil
	if fake.changedPagesSinceReturnsOnCall == nil {
		fake.changedPagesSinceReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 bool
		})
	}
	fake.changedPagesSinceReturnsOnCall[i] = struct {
		result1 []string
		result2 bool
	}{result1, result2}
}

func (fake *PageIndex) ForceReload() {
	fake.forceReloadMutex.Lock()
	fake.forceReloadArgsForCall = append(fake.forceReloadArgsForCall, struct{}{})
	stub := fake.ForceReloadStub
	fake.recordInvocation("ForceReload", []interface{}{})
	fake.forceReloadMutex.Unlock()
	if stub != nil {
		stub()
	}
}

func (fake *PageIndex) ForceReloadCallCount() int {
	fake.forceReloadMutex.RLock()
	defer fake.forceReloadMutex.RUnlock()
	return len(fake.forceReloadArgsForCall)
}

func (fake *PageIndex) ForceReloadCalls(stub func()) {
	fake.forceReloadMutex.Lock()
	defer fake.forceReloadMutex.Unlock()
	fake.ForceReloadStub = stub
}

func (fake *PageIndex) ListPages(arg1 context.Context, arg2 string, arg3 string) ([]*domain.Page, error) {
	fake.listPagesMutex.Lock()
	ret, specificReturn := fake.listPagesReturnsOnCall[len(fake.listPagesArgsForCall)]
	fake.listPagesArgsForCall = append(fake.listPagesArgsForCall, PageIndexListPagesArgs{arg1, arg2, arg3})
	stub := fake.ListPagesStub
	fakeReturns := fake.listPagesReturns
	fake.recordInvocation("ListPages", []interface{}{arg1, arg2, arg3})
	fake.listPagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PageIndex) ListPagesCallCount() int {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	return len(fake.listPagesArgsForCall)
}

func (fake *PageIndex) ListPagesCalls(stub func(context.Context, string, string) ([]*domain.Page, error)) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = stub
}

func (fake *PageIndex) ListPagesArgsForCall(i int) (context.Context, string, string) {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	argsForCall := fake.listPagesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *PageIndex) ListPagesArgs() []PageIndexListPagesArgs {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	args := make([]PageIndexListPagesArgs, len(fake.listPagesArgsForCall))
	copy(args, fake.listPagesArgsForCall)
	return args
}

func (fake *PageIndex) ListPagesReturns(result1 []*domain.Page, result2 error) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = nil
	fake.listPagesReturns = struct {
		result1 []*domain.Page
		result2 error
	}{result1, result2}
}

func (fake *PageIndex) ListPagesReturnsOnCall(i int, result1 []*domain.Page, result2 error) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = nil
	if fake.listPagesReturnsOnCall == nil {
		fake.listPagesReturnsOnCall = make(map[int]struct {
			result1 []*domain.Page
			result2 error
		})
	}
	fake.listPagesReturnsOnCall[i] = struct {
		result1 []*domain.Page
		result2 error
	}{result1, result2}
}

func (fake *PageIndex) MarkDirty(arg1 ...pageindex.Key) {
	var arg1Copy []pageindex.Key
	if arg1 != nil {
		arg1Copy = make([]pageindex.Key, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.markDirtyMutex.Lock()
	fake.markDirtyArgsForCall = append(fake.markDirtyArgsForCall, PageIndexMarkDirtyArgs{arg1Copy})
	stub := fake.MarkDirtyStub
	fake.recordInvocation("MarkDirty", []interface{}{arg1Copy})
	fake.markDirtyMutex.Unlock()
	if stub != nil {
		stub(arg1...)
	}
}

func (fake *PageIndex) MarkDirtyCallCount() int {
	fake.markDirtyMutex.RLock()
	defer fake.markDirtyMutex.RUnlock()
	return len(fake.markDirtyArgsForCall)
}

func (fake *PageIndex) MarkDirtyCalls(stub func(...pageindex.Key)) {
	fake.markDirtyMutex.Lock()
	defer fake.markDirtyMutex.Unlock()
	fake.MarkDirtyStub = stub
}

func (fake *PageIndex) MarkDirtyArgsForCall(i int) []pageindex.Key {
	fake.markDirtyMutex.RLock()
	defer fake.markDirtyMutex.RUnlock()
	argsForCall := fake.markDirtyArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *PageIndex) MarkDirtyArgs() []PageIndexMarkDirtyArgs {
	fake.markDirtyMutex.RLock()
	defer fake.markDirtyMutex.RUnlock()
	args := make([]PageIndexMarkDirtyArgs, len(fake.markDirtyArgsForCall))
	copy(args, fake.markDirtyArgsForCall)
	return args
}

func (fake *PageIndex) MarkFileDirty(arg1 pageindex.Key, arg2 string) {
	fake.markFileDirtyMutex.Lock()
	fake.markFileDirtyArgsForCall = append(fake.markFileDirtyArgsForCall, PageIndexMarkFileDirtyArgs{arg1, arg2})
	stub := fake.MarkFileDirtyStub
	fake.recordInvocation("MarkFileDirty", []interface{}{arg1, arg2})
	fake.markFileDirtyMutex.Unlock()
	if stub != nil {
		stub(arg1, arg2)
	}
}

func (fake *PageIndex) MarkFileDirtyCallCount() int {
	fake.markFileDirtyMutex.RLock()
	defer fake.markFileDirtyMutex.RUnlock()
	return len(fake.markFileDirtyArgsForCall)
}

func (fake *PageIndex) MarkFileDirtyCalls(stub func(pageindex.Key, string)) {
	fake.markFileDirtyMutex.Lock()
	defer fake.markFileDirtyMutex.Unlock()
	fake.MarkFileDirtyStub = stub
}

func (fake *PageIndex) MarkFileDirtyArgsForCall(i int) (pageindex.Key, string) {
	fake.markFileDirtyMutex.RLock()
	defer fake.markFileDirtyMutex.RUnlock()
	argsForCall := fake.markFileDirtyArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *PageIndex) MarkFileDirtyArgs() []PageIndexMarkFileDirtyArgs {
	fake.markFileDirtyMutex.RLock()
	defer fake.markFileDirtyMutex.RUnlock()
	args := make([]PageIndexMarkFileDirtyArgs, len(fake.markFileDirtyArgsForCall))
	copy(args, fake.markFileDirtyArgsForCall)
	return args
}

func (fake *PageIndex) ReadPage(arg1 context.Context, arg2 string, arg3 string, arg4 string) (*domain.Page, error) {
	fake.readPageMutex.Lock()
	ret, specificReturn := fake.readPageReturnsOnCall[len(fake.readPageArgsForCall)]
	fake.readPageArgsForCall = append(fake.readPageArgsForCall, PageIndexReadPageArgs{arg1, arg2, arg3, arg4})
	stub := fake.ReadPageStub
	fakeReturns := fake.readPageReturns
	fake.recordInvocation("ReadPage", []interface{}{arg1, arg2, arg3, arg4})
	fake.readPageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PageIndex) ReadPageCallCount() int {
	fake.readPageMutex.RLock()
	defer fake.readPageMutex.RUnlock()
	return len(fake.readPageArgsForCall)
}

func (fake *PageIndex) ReadPageCalls(stub func(context.Context, string, string, string) (*domain.Page, error)) {
	fake.readPageMutex.Lock()
	defer fake.readPageMutex.Unlock()
	fake.ReadPageStub = stub
}

func (fake *PageIndex) ReadPageArgsForCall(i int) (context.Context, string, string, string) {
	fake.readPageMutex.RLock()
	defer fake.readPageMutex.RUnlock()
	argsForCall := fake.readPageArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *PageIndex) ReadPageArgs() []PageIndexReadPageArgs {
	fake.readPageMutex.RLock()
	defer fake.readPageMutex.RUnlock()
	args := make([]PageIndexReadPageArgs, len(fake.readPageArgsForCall))
	copy(args, fake.readPageArgsForCall)
	return args
}

func (fake *PageIndex) ReadPageReturns(result1 *domain.Page, result2 error) {
	fake.readPageMutex.Lock()
	defer fake.readPageMutex.Unlock()
	fake.ReadPageStub = nil
	fake.readPageReturns = struct {
		result1 *domain.Page
		result2 error
	}{result1, result2}
}

func (fake *PageIndex) ReadPageReturnsOnCall(i int, result1 *domain.Page, result2 error) {
	fake.readPageMutex.Lock()
	defer fake.readPageMutex.Unlock()
	fake.ReadPageStub = nil
	if fake.readPageReturnsOnCall == nil {
		fake.readPageReturnsOnCall = make(map[int]struct {
			result1 *domain.Page
			result2 error
		})
	}
	fake.readPageReturnsOnCall[i] = struct {
		result1 *domain.Page
		result2 error
	}{result1, result2}
}

func (fake *PageIndex) Refresh(arg1 context.Context, arg2 pageindex.Key) error {
	fake.refreshMutex.Lock()
	ret, specificReturn := fake.refreshReturnsOnCall[len(fake.refreshArgsForCall)]
	fake.refreshArgsForCall = append(fake.refreshArgsForCall, PageIndexRefreshArgs{arg1, arg2})
	stub := fake.RefreshStub
	fakeReturns := fake.refreshReturns
	fake.recordInvocation("Refresh", []interface{}{arg1, arg2})
	fake.refreshMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) RefreshCallCount() int {
	fake.refreshMutex.RLock()
	defer fake.refreshMutex.RUnlock()
	return len(fake.refreshArgsForCall)
}

func (fake *PageIndex) RefreshCalls(stub func(context.Context, pageindex.Key) error) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = stub
}

func (fake *PageIndex) RefreshArgsForCall(i int) (context.Context, pageindex.Key) {
	fake.refreshMutex.RLock()
	defer fake.refreshMutex.RUnlock()
	argsForCall := fake.refreshArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *PageIndex) RefreshArgs() []PageIndexRefreshArgs {
	fake.refreshMutex.RLock()
	defer fake.refreshMutex.RUnlock()
	args := make([]PageIndexRefreshArgs, len(fake.refreshArgsForCall))
	copy(args, fake.refreshArgsForCall)
	return args
}

func (fake *PageIndex) RefreshReturns(result1 error) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = nil
	fake.refreshReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) RefreshReturnsOnCall(i int, result1 error) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = nil
	if fake.refreshReturnsOnCall == nil {
		fake.refreshReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.refreshReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) RefreshFile(arg1 context.Context, arg2 pageindex.Key, arg3 string) error {
	fake.refreshFileMutex.Lock()
	ret, specificReturn := fake.refreshFileReturnsOnCall[len(fake.refreshFileArgsForCall)]
	fake.refreshFileArgsForCall = append(fake.refreshFileArgsForCall, PageIndexRefreshFileArgs{arg1, arg2, arg3})
	stub := fake.RefreshFileStub
	fakeReturns := fake.refreshFileReturns
	fake.recordInvocation("RefreshFile", []interface{}{arg1, arg2, arg3})
	fake.refreshFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) RefreshFileCallCount() int {
	fake.refreshFileMutex.RLock()
	defer fake.refreshFileMutex.RUnlock()
	return len(fake.refreshFileArgsForCall)
}

func (fake *PageIndex) RefreshFileCalls(stub func(context.Context, pageindex.Key, string) error) {
	fake.refreshFileMutex.Lock()
	defer fake.refreshFileMutex.Unlock()
	fake.RefreshFileStub = stub
}

func (fake *PageIndex) RefreshFileArgsForCall(i int) (context.Context, pageindex.Key, string) {
	fake.refreshFileMutex.RLock()
	defer fake.refreshFileMutex.RUnlock()
	argsForCall := fake.refreshFileArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *PageIndex) RefreshFileArgs() []PageIndexRefreshFileArgs {
	fake.refreshFileMutex.RLock()
	defer fake.refreshFileMutex.RUnlock()
	args := make([]PageIndexRefreshFileArgs, len(fake.refreshFileArgsForCall))
	copy(args, fake.refreshFileArgsForCall)
	return args
}

func (fake *PageIndex) RefreshFileReturns(result1 error) {
	fake.refreshFileMutex.Lock()
	defer fake.refreshFileMutex.Unlock()
	fake.RefreshFileStub = nil
	fake.refreshFileReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) RefreshFileReturnsOnCall(i int, result1 error) {
	fake.refreshFileMutex.Lock()
	defer fake.refreshFileMutex.Unlock()
	fake.RefreshFileStub = nil
	if fake.refreshFileReturnsOnCall == nil {
		fake.refreshFileReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.refreshFileReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) Rescan(arg1 context.Context) error {
	fake.rescanMutex.Lock()
	ret, specificReturn := fake.rescanReturnsOnCall[len(fake.rescanArgsForCall)]
	fake.rescanArgsForCall = append(fake.rescanArgsForCall, PageIndexRescanArgs{arg1})
	stub := fake.RescanStub
	fakeReturns := fake.rescanReturns
	fake.recordInvocation("Rescan", []interface{}{arg1})
	fake.rescanMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) RescanCallCount() int {
	fake.rescanMutex.RLock()
	defer fake.rescanMutex.RUnlock()
	return len(fake.rescanArgsForCall)
}

func (fake *PageIndex) RescanCalls(stub func(context.Context) error) {
	fake.rescanMutex.Lock()
	defer fake.rescanMutex.Unlock()
	fake.RescanStub = stub
}

func (fake *PageIndex) RescanArgsForCall(i int) context.Context {
	fake.rescanMutex.RLock()
	defer fake.rescanMutex.RUnlock()
	argsForCall := fake.rescanArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *PageIndex) RescanArgs() []PageIndexRescanArgs {
	fake.rescanMutex.RLock()
	defer fake.rescanMutex.RUnlock()
	args := make([]PageIndexRescanArgs, len(fake.rescanArgsForCall))
	copy(args, fake.rescanArgsForCall)
	return args
}

func (fake *PageIndex) RescanReturns(result1 error) {
	fake.rescanMutex.Lock()
	defer fake.rescanMutex.Unlock()
	fake.RescanStub = nil
	fake.rescanReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) RescanReturnsOnCall(i int, result1 error) {
	fake.rescanMutex.Lock()
	defer fake.rescanMutex.Unlock()
	fake.RescanStub = nil
	if fake.rescanReturnsOnCall == nil {
		fake.rescanReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.rescanReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) Revision(arg1 pageindex.Key) uint64 {
	fake.revisionMutex.Lock()
	ret, specificReturn := fake.revisionReturnsOnCall[len(fake.revisionArgsForCall)]
	fake.revisionArgsForCall = append(fake.revisionArgsForCall, PageIndexRevisionArgs{arg1})
	stub := fake.RevisionStub
	fakeReturns := fake.revisionReturns
	fake.recordInvocation("Revision", []interface{}{arg1})
	fake.revisionMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) RevisionCallCount() int {
	fake.revisionMutex.RLock()
	defer fake.revisionMutex.RUnlock()
	return len(fake.revisionArgsForCall)
}

func (fake *PageIndex) RevisionCalls(stub func(pageindex.Key) uint64) {
	fake.revisionMutex.Lock()
	defer fake.revisionMutex.Unlock()
	fake.RevisionStub = stub
}

func (fake *PageIndex) RevisionArgsForCall(i int) pageindex.Key {
	fake.revisionMutex.RLock()
	defer fake.revisionMutex.RUnlock()
	argsForCall := fake.revisionArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *PageIndex) RevisionArgs() []PageIndexRevisionArgs {
	fake.revisionMutex.RLock()
	defer fake.revisionMutex.RUnlock()
	args := make([]PageIndexRevisionArgs, len(fake.revisionArgsForCall))
	copy(args, fake.revisionArgsForCall)
	return args
}

func (fake *PageIndex) RevisionReturns(result1 uint64) {
	fake.revisionMutex.Lock()
	defer fake.revisionMutex.Unlock()
	fake.RevisionStub = nil
	fake.revisionReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *PageIndex) RevisionReturnsOnCall(i int, result1 uint64) {
	fake.revisionMutex.Lock()
	defer fake.revisionMutex.Unlock()
	fake.RevisionStub = nil
	if fake.revisionReturnsOnCall == nil {
		fake.revisionReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.revisionReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *PageIndex) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PageIndex) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *PageIndex) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pageindex.PageIndex = new(PageIndex)
