// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-ui/pkg/pageindex"
)

type DirectoryLister struct {
	ListFilesStub        func(context.Context, string, string) ([]pageindex.FileEntry, error)
	listFilesMutex       sync.RWMutex
	listFilesArgsForCall []DirectoryListerListFilesArgs
	listFilesReturns     struct {
		result1 []pageindex.FileEntry
		result2 error
	}
	listFilesReturnsOnCall map[int]struct {
		result1 []pageindex.FileEntry
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// DirectoryListerListFilesArgs holds the arguments of one call to ListFiles.
type DirectoryListerListFilesArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
}

func (fake *DirectoryLister) ListFiles(arg1 context.Context, arg2 string, arg3 string) ([]pageindex.FileEntry, error) {
	fake.listFilesMutex.Lock()
	ret, specificReturn := fake.listFilesReturnsOnCall[len(fake.listFilesArgsForCall)]
	fake.listFilesArgsForCall = append(fake.listFilesArgsForCall, DirectoryListerListFilesArgs{arg1, arg2, arg3})
	stub := fake.ListFilesStub
	fakeReturns := fake.listFilesReturns
	fake.recordInvocation("ListFiles", []interface{}{arg1, arg2, arg3})
	fake.listFilesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *DirectoryLister) ListFilesCallCount() int {
	fake.listFilesMutex.RLock()
	defer fake.listFilesMutex.RUnlock()
	return len(fake.listFilesArgsForCall)
}

func (fake *DirectoryLister) ListFilesCalls(stub func(context.Context, string, string) ([]pageindex.FileEntry, error)) {
	fake.listFilesMutex.Lock()
	defer fake.listFilesMutex.Unlock()
	fake.ListFilesStub = stub
}

func (fake *DirectoryLister) ListFilesArgsForCall(i int) (context.Context, string, string) {
	fake.listFilesMutex.RLock()
	defer fake.listFilesMutex.RUnlock()
	argsForCall := fake.listFilesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *DirectoryLister) ListFilesArgs() []DirectoryListerListFilesArgs {
	fake.listFilesMutex.RLock()
	defer fake.listFilesMutex.RUnlock()
	args := make([]DirectoryListerListFilesArgs, len(fake.listFilesArgsForCall))
	copy(args, fake.listFilesArgsForCall)
	return args
}

func (fake *DirectoryLister) ListFilesReturns(result1 []pageindex.FileEntry, result2 error) {
	fake.listFilesMutex.Lock()
	defer fake.listFilesMutex.Unlock()
	fake.ListFilesStub = nil
	fake.listFilesReturns = struct {
		result1 []pageindex.FileEntry
		result2 error
	}{result1, result2}
}

func (fake *DirectoryLister) ListFilesReturnsOnCall(i int, result1 []pageindex.FileEntry, result2 error) {
	fake.listFilesMutex.Lock()
	defer fake.listFilesMutex.Unlock()
	fake.ListFilesStub = nil
	if fake.listFilesReturnsOnCall == nil {
		fake.listFilesReturnsOnCall = make(map[int]struct {
			result1 []pageindex.FileEntry
			result2 error
		})
	}
	fake.listFilesReturnsOnCall[i] = struct {
		result1 []pageindex.FileEntry
		result2 error
	}{result1, result2}
}

func (fake *DirectoryLister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DirectoryLister) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *DirectoryLister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pageindex.DirectoryLister = new(DirectoryLister)
