// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/vault-cli/pkg/domain"
	"github.com/bborbe/vault-ui/pkg/pageindex"
)

type PageIndex struct {
	BuildStub        func(context.Context, []pageindex.Key) error
	buildMutex       sync.RWMutex
	buildArgsForCall []PageIndexBuildArgs
	buildReturns     struct {
		result1 error
	}
	buildReturnsOnCall map[int]struct {
		result1 error
	}
	ListPagesStub        func(context.Context, string, string) ([]*domain.Page, error)
	listPagesMutex       sync.RWMutex
	listPagesArgsForCall []PageIndexListPagesArgs
	listPagesReturns     struct {
		result1 []*domain.Page
		result2 error
	}
	listPagesReturnsOnCall map[int]struct {
		result1 []*domain.Page
		result2 error
	}
	MarkAllDirtyStub        func()
	markAllDirtyMutex       sync.RWMutex
	markAllDirtyArgsForCall []struct{}
	MarkDirtyStub           func(...pageindex.Key)
	markDirtyMutex          sync.RWMutex
	markDirtyArgsForCall    []PageIndexMarkDirtyArgs
	RefreshStub             func(context.Context, pageindex.Key) error
	refreshMutex            sync.RWMutex
	refreshArgsForCall      []PageIndexRefreshArgs
	refreshReturns          struct {
		result1 error
	}
	refreshReturnsOnCall map[int]struct {
		result1 error
	}
	RescanStub        func(context.Context) error
	rescanMutex       sync.RWMutex
	rescanArgsForCall []PageIndexRescanArgs
	rescanReturns     struct {
		result1 error
	}
	rescanReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// PageIndexBuildArgs holds the arguments of one call to Build.
type PageIndexBuildArgs struct {
	Arg1 context.Context
	Arg2 []pageindex.Key
}

// PageIndexListPagesArgs holds the arguments of one call to ListPages.
type PageIndexListPagesArgs struct {
	Arg1 context.Context
	Arg2 string
	Arg3 string
}

// PageIndexMarkDirtyArgs holds the arguments of one call to MarkDirty.
type PageIndexMarkDirtyArgs struct {
	Arg1 []pageindex.Key
}

// PageIndexRefreshArgs holds the arguments of one call to Refresh.
type PageIndexRefreshArgs struct {
	Arg1 context.Context
	Arg2 pageindex.Key
}

// PageIndexRescanArgs holds the arguments of one call to Rescan.
type PageIndexRescanArgs struct {
	Arg1 context.Context
}

func (fake *PageIndex) Build(arg1 context.Context, arg2 []pageindex.Key) error {
	var arg2Copy []pageindex.Key
	if arg2 != nil {
		arg2Copy = make([]pageindex.Key, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.buildMutex.Lock()
	ret, specificReturn := fake.buildReturnsOnCall[len(fake.buildArgsForCall)]
	fake.buildArgsForCall = append(fake.buildArgsForCall, PageIndexBuildArgs{arg1, arg2Copy})
	stub := fake.BuildStub
	fakeReturns := fake.buildReturns
	fake.recordInvocation("Build", []interface{}{arg1, arg2Copy})
	fake.buildMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *PageIndex) BuildCalls(stub func(context.Context, []pageindex.Key) error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = stub
}

func (fake *PageIndex) BuildArgsForCall(i int) (context.Context, []pageindex.Key) {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	argsForCall := fake.buildArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *PageIndex) BuildArgs() []PageIndexBuildArgs {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	args := make([]PageIndexBuildArgs, len(fake.buildArgsForCall))
	copy(args, fake.buildArgsForCall)
	return args
}

func (fake *PageIndex) BuildReturns(result1 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) BuildReturnsOnCall(i int, result1 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	if fake.buildReturnsOnCall == nil {
		fake.buildReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.buildReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) ListPages(arg1 context.Context, arg2 string, arg3 string) ([]*domain.Page, error) {
	fake.listPagesMutex.Lock()
	ret, specificReturn := fake.listPagesReturnsOnCall[len(fake.listPagesArgsForCall)]
	fake.listPagesArgsForCall = append(fake.listPagesArgsForCall, PageIndexListPagesArgs{arg1, arg2, arg3})
	stub := fake.ListPagesStub
	fakeReturns := fake.listPagesReturns
	fake.recordInvocation("ListPages", []interface{}{arg1, arg2, arg3})
	fake.listPagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *PageIndex) ListPagesCallCount() int {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	return len(fake.listPagesArgsForCall)
}

func (fake *PageIndex) ListPagesCalls(stub func(context.Context, string, string) ([]*domain.Page, error)) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = stub
}

func (fake *PageIndex) ListPagesArgsForCall(i int) (context.Context, string, string) {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	argsForCall := fake.listPagesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *PageIndex) ListPagesArgs() []PageIndexListPagesArgs {
	fake.listPagesMutex.RLock()
	defer fake.listPagesMutex.RUnlock()
	args := make([]PageIndexListPagesArgs, len(fake.listPagesArgsForCall))
	copy(args, fake.listPagesArgsForCall)
	return args
}

func (fake *PageIndex) ListPagesReturns(result1 []*domain.Page, result2 error) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = nil
	fake.listPagesReturns = struct {
		result1 []*domain.Page
		result2 error
	}{result1, result2}
}

func (fake *PageIndex) ListPagesReturnsOnCall(i int, result1 []*domain.Page, result2 error) {
	fake.listPagesMutex.Lock()
	defer fake.listPagesMutex.Unlock()
	fake.ListPagesStub = nil
	if fake.listPagesReturnsOnCall == nil {
		fake.listPagesReturnsOnCall = make(map[int]struct {
			result1 []*domain.Page
			result2 error
		})
	}
	fake.listPagesReturnsOnCall[i] = struct {
		result1 []*domain.Page
		result2 error
	}{result1, result2}
}

func (fake *PageIndex) MarkAllDirty() {
	fake.markAllDirtyMutex.Lock()
	fake.markAllDirtyArgsForCall = append(fake.markAllDirtyArgsForCall, struct{}{})
	stub := fake.MarkAllDirtyStub
	fake.recordInvocation("MarkAllDirty", []interface{}{})
	fake.markAllDirtyMutex.Unlock()
	if stub != nil {
		stub()
	}
}

func (fake *PageIndex) MarkAllDirtyCallCount() int {
	fake.markAllDirtyMutex.RLock()
	defer fake.markAllDirtyMutex.RUnlock()
	return len(fake.markAllDirtyArgsForCall)
}

func (fake *PageIndex) MarkAllDirtyCalls(stub func()) {
	fake.markAllDirtyMutex.Lock()
	defer fake.markAllDirtyMutex.Unlock()
	fake.MarkAllDirtyStub = stub
}

func (fake *PageIndex) MarkDirty(arg1 ...pageindex.Key) {
	var arg1Copy []pageindex.Key
	if arg1 != nil {
		arg1Copy = make([]pageindex.Key, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.markDirtyMutex.Lock()
	fake.markDirtyArgsForCall = append(fake.markDirtyArgsForCall, PageIndexMarkDirtyArgs{arg1Copy})
	stub := fake.MarkDirtyStub
	fake.recordInvocation("MarkDirty", []interface{}{arg1Copy})
	fake.markDirtyMutex.Unlock()
	if stub != nil {
		stub(arg1...)
	}
}

func (fake *PageIndex) MarkDirtyCallCount() int {
	fake.markDirtyMutex.RLock()
	defer fake.markDirtyMutex.RUnlock()
	return len(fake.markDirtyArgsForCall)
}

func (fake *PageIndex) MarkDirtyCalls(stub func(...pageindex.Key)) {
	fake.markDirtyMutex.Lock()
	defer fake.markDirtyMutex.Unlock()
	fake.MarkDirtyStub = stub
}

func (fake *PageIndex) MarkDirtyArgsForCall(i int) []pageindex.Key {
	fake.markDirtyMutex.RLock()
	defer fake.markDirtyMutex.RUnlock()
	argsForCall := fake.markDirtyArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *PageIndex) MarkDirtyArgs() []PageIndexMarkDirtyArgs {
	fake.markDirtyMutex.RLock()
	defer fake.markDirtyMutex.RUnlock()
	args := make([]PageIndexMarkDirtyArgs, len(fake.markDirtyArgsForCall))
	copy(args, fake.markDirtyArgsForCall)
	return args
}

func (fake *PageIndex) Refresh(arg1 context.Context, arg2 pageindex.Key) error {
	fake.refreshMutex.Lock()
	ret, specificReturn := fake.refreshReturnsOnCall[len(fake.refreshArgsForCall)]
	fake.refreshArgsForCall = append(fake.refreshArgsForCall, PageIndexRefreshArgs{arg1, arg2})
	stub := fake.RefreshStub
	fakeReturns := fake.refreshReturns
	fake.recordInvocation("Refresh", []interface{}{arg1, arg2})
	fake.refreshMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) RefreshCallCount() int {
	fake.refreshMutex.RLock()
	defer fake.refreshMutex.RUnlock()
	return len(fake.refreshArgsForCall)
}

func (fake *PageIndex) RefreshCalls(stub func(context.Context, pageindex.Key) error) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = stub
}

func (fake *PageIndex) RefreshArgsForCall(i int) (context.Context, pageindex.Key) {
	fake.refreshMutex.RLock()
	defer fake.refreshMutex.RUnlock()
	argsForCall := fake.refreshArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *PageIndex) RefreshArgs() []PageIndexRefreshArgs {
	fake.refreshMutex.RLock()
	defer fake.refreshMutex.RUnlock()
	args := make([]PageIndexRefreshArgs, len(fake.refreshArgsForCall))
	copy(args, fake.refreshArgsForCall)
	return args
}

func (fake *PageIndex) RefreshReturns(result1 error) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = nil
	fake.refreshReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) RefreshReturnsOnCall(i int, result1 error) {
	fake.refreshMutex.Lock()
	defer fake.refreshMutex.Unlock()
	fake.RefreshStub = nil
	if fake.refreshReturnsOnCall == nil {
		fake.refreshReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.refreshReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) Rescan(arg1 context.Context) error {
	fake.rescanMutex.Lock()
	ret, specificReturn := fake.rescanReturnsOnCall[len(fake.rescanArgsForCall)]
	fake.rescanArgsForCall = append(fake.rescanArgsForCall, PageIndexRescanArgs{arg1})
	stub := fake.RescanStub
	fakeReturns := fake.rescanReturns
	fake.recordInvocation("Rescan", []interface{}{arg1})
	fake.rescanMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *PageIndex) RescanCallCount() int {
	fake.rescanMutex.RLock()
	defer fake.rescanMutex.RUnlock()
	return len(fake.rescanArgsForCall)
}

func (fake *PageIndex) RescanCalls(stub func(context.Context) error) {
	fake.rescanMutex.Lock()
	defer fake.rescanMutex.Unlock()
	fake.RescanStub = stub
}

func (fake *PageIndex) RescanArgsForCall(i int) context.Context {
	fake.rescanMutex.RLock()
	defer fake.rescanMutex.RUnlock()
	argsForCall := fake.rescanArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *PageIndex) RescanArgs() []PageIndexRescanArgs {
	fake.rescanMutex.RLock()
	defer fake.rescanMutex.RUnlock()
	args := make([]PageIndexRescanArgs, len(fake.rescanArgsForCall))
	copy(args, fake.rescanArgsForCall)
	return args
}

func (fake *PageIndex) RescanReturns(result1 error) {
	fake.rescanMutex.Lock()
	defer fake.rescanMutex.Unlock()
	fake.RescanStub = nil
	fake.rescanReturns = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) RescanReturnsOnCall(i int, result1 error) {
	fake.rescanMutex.Lock()
	defer fake.rescanMutex.Unlock()
	fake.RescanStub = nil
	if fake.rescanReturnsOnCall == nil {
		fake.rescanReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.rescanReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *PageIndex) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *PageIndex) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *PageIndex) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pageindex.PageIndex = new(PageIndex)
